[package]
name = "krust-cli"
version = "0.1.0"
authors = ["Robert Glyde <robert.glyde@sky.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdkafka = { version = "~0.21", features = ["dynamic_linking"] }
futures = "0.1.20"
uuid = { version = "0.7", features = ["v4"] }
tokio = "0.1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.3.1"
indicatif = "0.12.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
